# Generated by Django 4.1.2 on 2022-11-07 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_name_alter_amenity_descriptions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.AddField(
            model_name="amenity",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 8, 4, 22, 58, 930167)
            ),
        ),
        migrations.AddField(
            model_name="amenity",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 8, 4, 22, 58, 930167)
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 8, 4, 22, 58, 930167)
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 8, 4, 22, 58, 930167)
            ),
        ),
    ]
